lita:
  volumes:
    - .:/code
  build: .
  links:
    - brain
  env_file:
    - ./.envrc
  environment:
    - LITA_LOG_LEVEL=debug
  ports:
    - '8080:8080'

brain:
  image: redis:latest
  volumes:
    - /opt/dorkbot/data:/data
